<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Rental Contract</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 13px;
            color: #333;
            line-height: 1.6;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            color: #1d4ed8;
        }

        .section {
            margin-top: 20px;
        }

        .section h3 {
            background: #1d4ed8;
            color: white;
            padding: 8px;
            margin-bottom: 8px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table td,
        table th {
            border: 1px solid #ccc;
            padding: 8px;
        }

        .terms {
            font-size: 12px;
        }

        .signature {
            margin-top: 60px;
        }

        .signature td {
            border: none;
            text-align: center;
            padding-top: 50px;
        }

        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 11px;
            color: gray;
        }
    </style>

</head>

<body>

    <div class="header">
        <h1>AutoOne Car Rental</h1>
        <h2>Digital Rental Agreement</h2>
        <p>Contract Date : {{ $today }}</p>
    </div>

    <div class="section">
        <h3>Customer Information</h3>

        <table>
            <tr>
                <th width="30%">Name</th>
                <td>{{ $customer->name }}</td>
            </tr>

            <tr>
                <th>Email</th>
                <td>{{ $customer->email }}</td>
            </tr>

            <tr>
                <th>Phone</th>
                <td>{{ $customer->phone ?? '-' }}</td>
            </tr>

            <tr>
                <th>Address</th>
                <td>{{ $customer->address ?? '-' }}</td>
            </tr>
        </table>
    </div>

    <div class="section">

        <h3>Vehicle Information</h3>

        <table>

            <tr>
                <th width="30%">Brand</th>
                <td>{{ $car->carBrand->name ?? '-' }}</td>
            </tr>

            <tr>
                <th>Year</th>
                <td>{{ $car->year }}</td>
            </tr>

        </table>

    </div>

    <div class="section">

        <h3>Rental Details</h3>

        <table>

            <tr>
                <th width="30%">Booking ID</th>
                <td>#{{ $booking->id }}</td>
            </tr>

            <tr>
                <th>Start Date</th>
                <td>{{ $booking->pickup_date }}</td>
            </tr>

            <tr>
                <th>End Date</th>
                <td>{{ $booking->return_date }}</td>
            </tr>

            <tr>
                <th>Total Price</th>
                <td>{{ $total }} USD </td>
            </tr>

            <tr>
                <th>Status</th>
                <td>{{ $booking->status }}</td>
            </tr>

        </table>

    </div>

    <div class="section">

        <h3>Rental Terms & Conditions</h3>

        <div class="terms">

            <ol>

                <li>The renter must possess a valid driving license.</li>

                <li>The vehicle shall only be used for lawful purposes.</li>

                <li>No reckless driving or racing is permitted.</li>

                <li>The renter is responsible for traffic fines.</li>

                <li>The vehicle must be returned on the agreed date.</li>

                <li>Late returns may incur additional charges.</li>

                <li>The renter is liable for damages caused by negligence.</li>

                <li>The company reserves the right to terminate this agreement if any terms are violated.</li>

            </ol>

        </div>

    </div>

    <div class="signature">

        <table>

            <tr>

                <td>
                    _______________________<br>
                    Customer Signature
                </td>

                <td>
                    _______________________<br>
                    Company Representative
                </td>

            </tr>

        </table>

    </div>

    <div class="footer">

        This document is electronically generated by AutoOne and is valid without a physical signature.

    </div>

</body>

</html>